### ISSUE TITLE
Incorrect (negative) values in safeRound result

### ISSUE THREAD

**Issue by wiese** [boredland/saferound#134]
For certain inputs (not entirely sure what they have in common) we are seeing results which do seem off and do not match [Iteround](https://github.com/cgdeboer/iteround)'s results for the same input.

Interestingly, a correct sum seems to be achieved by negative and positive values compensating for one another.

Please find a reproduction at https://github.com/wiese/saferound/commit/0bacbbc99c3853f7d28711e02b6f108c4c298092

The iteround equivalent (codesandbox [here](https://codesandbox.io/p/sandbox/cocky-poitras-rgcrzu?file=%2Fmain.py)):

```
import iteround

data = {
    'a': 0.013245557004700679,
    'b': 0.7268604797100215,
    'c': 0.6155001637295456,
    'd': 0.06875329582046738,
    'e': 0.8387831576913838,
    'f': 0.03243429881206358,
    'g': 0.0023860988000495792,
    'h': 0.41960946536150784,
    'i': 0.675551119386058,
    'j': 0.6409523907667709,
    'k': 0.9659239729174308,
}

print(sum(data.values())) // 4.999999999999999

rounded = iteround.saferound(data, 0)

print(sum(rounded.values())) // 5.0
print(rounded.values()) // dict_values([0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0])
```

Please advise, am I missing something? Thank you!

**Comment by boredland** [comment]
Well, I guess I removed too much comparing with the original implementation. Pushed a bug fix that should align it. At least your test became green and while the order of things changed, the sum-result remained stable throughout the pre-exising tests.

**Comment by wiese** [comment]
Thanks for the swift reaction. The suggested regression test is now green.

However, after this change that's not the case for [the pre-existing example in the test suite](https://github.com/boredland/saferound/commit/1f382943a64f2d9274f233213c60dae10a8962c8#diff-0cdc78cf509e12b72f87fbf147de34e8e3d4fb3d39ac49bdb21d16b0f84de514R37) 
| input | `4.0001, 3.2345, 3.2321, 6.4523, 5.3453, 7.3422` |
| ------------- | ------------- |
| saferound |`5, 3, 4, 6, 5, 7` |
| iteround | `4.0, 3.0, 3.0, 7.0, 6.0, 7.0` |

nor for [the example of the iteround package](https://github.com/cgdeboer/iteround/tree/v1.0.4#iteround-sum-safe-rounding-for-iterables)

| input | `60.19012964572332, 15.428802458406679, 24.381067895870007` |
| ------------- | ------------- |
| saferound | `61, 15, 24` |
| iteround |`60.0, 16.0, 24.0` |

It was my understanding that saferound tries to produce the same results as iteround. Is there a misunderstanding?

Thanks!

**Comment by boredland** [comment]
nvm, I think I have been able to fix it so, that the original basic difference [test](https://github.com/cgdeboer/iteround/blob/master/tests/test_saferound.py#L18) as well as the readme example are green.
